import type { Metadata } from "next";
import { SITE_CONTACT } from "@/config/site";

export const metadata: Metadata = { title: "Analitik ve gizlilik", description: "Beyin Deposu analitik verileri, çerez tercihleri ve kişisel veri hakları." };

export default function PrivacyPage() {
  return <article className="container max-w-3xl space-y-8 py-12 text-sm leading-relaxed text-slate-700">
    <h1 className="text-3xl font-medium text-slate-900">Analitik ve gizlilik</h1>
    <section className="space-y-3"><h2 className="text-lg font-medium text-slate-900">Amaç ve kapsam</h2><p>Beyin Deposu, kataloğunu ve site kullanımını iyileştirmek için yalnızca analitik izni veren ziyaretçilerin kullanım hareketlerini ölçer. İzin, siteyi kullanmanın şartı değildir. Bu metin analitik ölçüme ilişkindir; iletişim ve canlı destek işlemleri kendi hizmet amaçlarıyla yürütülür.</p></section>
    <section className="space-y-3"><h2 className="text-lg font-medium text-slate-900">Ölçülen veriler</h2><p>Sayfa ve ürün açılmaları, katalogda aranan parça/OEM terimleri, sonuç bulunamaması, kullanılan filtreler, katalog sayfalama, görsel seçimi ve yakınlaştırma, OEM ve bağlantı kopyalama, aktif süre, WhatsApp/telefon/e-posta tıklamaları ve sohbet açma/başlatma/mesaj gönderme sayıları ölçülür. Kaba cihaz sınıfı ve trafik kaynağı kategorisi de kaydedilir.</p><p>İsim, telefon, e-posta, sohbet veya form içeriği, VIN, hesap kimliği, tam yönlendiren adres, URL sorgu parametreleri ve hassas girdi içerikleri analitik kaydına eklenmez. Tanınmayan serbest metin aramalar gizlenir; doğrulanan katalog terimleri ve uygun parça kodları tutulur. Ekran kaydı ve cihaz parmak izi kullanılmaz. Analitik veritabanına IP adresi yazılmaz; bağlantının kurulması için hizmet sağlayıcıların IP işlemesi ve erişim kayıtları ayrıca değerlendirilmelidir.</p><p>Rastgele tarayıcı ve oturum tanımlayıcıları takma adlı kişisel veri olarak ele alınır; müşteri hesapları veya canlı destek kimlikleriyle birleştirilmez. Tarayıcı değiştirmek, çerezleri silmek veya tanımlayıcı süresinin dolması yeni bir ziyaretçi sayılmasına neden olabilir.</p></section>
    <section className="space-y-3"><h2 className="text-lg font-medium text-slate-900">Tercihler ve saklama süreleri</h2><p>Analitik için hukuki sebep açık rızanızdır. Kabul ve ret tercihiniz 180 gün saklanır. Rıza sürümü ve verildiği zaman, ölçülen oturumun kaydında yer alır. Analitik tanımlayıcı çerez 90 gün, oturum çerezi son ölçümden itibaren 30 dakika geçerlidir. Hareketler, oturumlar ve tekil sayım kayıtları 90 gün; kişi tanımlayıcısı içermeyen istatistik toplamları en fazla 400 gün saklanır. Süresi dolan kayıtlar altı saatte bir başlayan temizlikle silinir.</p><p>Alt bilgideki “Çerez tercihleri” ile izninizi geri alabilir ve mevcut tarayıcınıza ait analitik kayıtlarının silinmesini isteyebilirsiniz. İzleme hemen durur; ayrıntılı kayıtlar silme kuyruğuna alınır. Bağlantı hatasında silme isteğini yeniden gönderebilmek için yalnızca silmeye yarayan geçici bir makbuz çerez tutulur. Kişi tanımlayıcısı içermeyen toplu istatistikler korunur. Eski veya başka tarayıcıya ait kayıtlar için bizimle iletişime geçebilirsiniz.</p></section>
    <section className="space-y-3"><h2 className="text-lg font-medium text-slate-900">Hizmet sağlayıcı ve aktarım</h2><p>Analitik, site sunucusu üzerinden Convex altyapısında işlenir. Yeni analitik sistemi Google Analytics veya reklam platformlarına veri göndermez. Veri işleme bölgesi yurt dışındaysa, sürekli aktarım için KVKK’nın 9. maddesine uygun aktarım koşulları ayrıca sağlanmalıdır; çerez kabulü tek başına aktarım dayanağı olarak kullanılmaz. Sistemin etkinleştirilmesi, veri sorumlusunun sağlayıcı, bölge, saklama ve aktarım koşullarını doğrulamasına bağlıdır.</p></section>
    <section className="space-y-3"><h2 className="text-lg font-medium text-slate-900">Haklarınız ve iletişim</h2><p>6698 sayılı Kanun’un 11. maddesi kapsamında kişisel verilerinizin işlenip işlenmediğini öğrenme, bilgi talep etme, işleme amacını ve aktarılan tarafları öğrenme, düzeltme veya silme isteme ve kanundaki diğer haklarınızı kullanabilirsiniz.</p><p>Beyin Deposu · {SITE_CONTACT.address}<br />İletişim: <a className="text-blue-700 underline" href={`mailto:${SITE_CONTACT.email}`}>{SITE_CONTACT.email}</a></p></section>
    <p className="text-xs text-slate-500">Metin sürümü: 1 Ekim 2026</p>
  </article>;
}
